steps:
  # We need to install locally in order to test the app
  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'cp .npmrc.ci .npmrc']
  # Uses node rather than cloudbuilder for a newer version of npm
  - name: 'node:10'
    entrypoint: npm
    args: ['install']
    secretEnv: ['NPM_TOKEN']
  - name: 'node:10'
    entrypoint: npm
    args: ['test']
    secretEnv: ['NPM_TOKEN'] # NPM doesn't like having an incomplete .npmrc, so this needs to be there even if not used
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg NPM_TOKEN=$$NPM_TOKEN -t gcr.io/$PROJECT_ID/canal-graph .']
    secretEnv: ['NPM_TOKEN']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/canal-graph', 'gcr.io/canalapp/$PROJECT_ID/canal-graph:$SHORT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/canal-graph'
  - 'gcr.io/$PROJECT_ID/canal-graph:$SHORT_SHA'

secrets:
  - kmsKeyName: projects/canalapp/locations/global/keyRings/canal-build/cryptoKeys/prod-secrets
    secretEnv:
      NPM_TOKEN: CiQAbBfdXmnGDJmp8wjlcmk9XZu3desUvSUHAlP+PCfgRd4gz7ESUgCZosN6sYyK1oXjz2TLpAVLvQD7kBOqhsDpFSJoxMJ52UuW6NmEYVMx8ReErQE0pYqrc7IOa9RZWXMKgTFaVhy31Mqp9zi1pS4GvI/IZkrsGE8=
