steps:
  # We need to install locally in order to test the app
  - name: 'ubuntu'
    args: ['bash', './configureci.sh']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    secretEnv: ['NPM_TOKEN']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg NPM_TOKEN=$$NPM_TOKEN -t gcr.io/$PROJECT_ID/canal-graph .']
    secretEnv: ['NPM_TOKEN']
images:
  - 'gcr.io/$PROJECT_ID/canal-graph'

secrets:
  - kmsKeyName: projects/canalapp/locations/global/keyRings/canal-build/cryptoKeys/prod-secrets
    secretEnv:
      NPM_TOKEN: CiQAbBfdXmnGDJmp8wjlcmk9XZu3desUvSUHAlP+PCfgRd4gz7ESUgCZosN6sYyK1oXjz2TLpAVLvQD7kBOqhsDpFSJoxMJ52UuW6NmEYVMx8ReErQE0pYqrc7IOa9RZWXMKgTFaVhy31Mqp9zi1pS4GvI/IZkrsGE8=
